### PR TITLE
Coinbase TX improvements

### PR DESCRIPTION
**Pull request by AlimovSV**
- Fix the coinbase transaction's nonce. Use a mining account's nonce as discussed with @malroc 
- Improve test suite
- Refactoring

### CODE REVIEW

**Comment by AlimovSV** [comment]
Btw, [this](https://github.com/turinginc/credo-core-node/blob/coinbase-tx/lib/credo_core_node/mining/coinbase_transaction.ex#L40) should be redundant because 1) Maps has unspecified keys order and 2) we are use our own JSON encoder

**Comment by macgregordennis** [comment]
> Btw, this should be redundant because 1) Maps has unspecified keys order and 2) we are use our own JSON encoder. Isn't?

@AlimovSV Right

**Comment by AlimovSV** [comment]
@macgregordennis Looks like you have some collisions with Ivan's PR. This errors occurs when the previous block doesn't have any votes:

**Comment by AlimovSV** [comment]
@macgregordennis I asked Oleg regarding votes. At the moment we collects ALL votes for all rounds and for all blocks. (1M blocks * 1000miners). It is not good for local mnesia data. Oleg suggests remove previous votes (before last block vote). What do you think - is it ok to do it in the `announce_block_is_locally_validated`?

**Comment by macgregordennis** [comment]
> Oleg suggests remove previous votes (before last block vote). What do you think - is it ok to do it in the announce_block_is_locally_validated (like removing pending transactions)?

Yes, though I'd prefer to have a slightly longer retention period, such as garbage collecting all votes that were cast for block numbers prior to the last confirmed block minus the lineage threshold (i.e. `block_number < CredoCoreNode.Blockchain.last_irreversible_block_number()`.

**Comment by macgregordennis** [comment]
> Looks like you have some collisions with Ivan's PR in the local mnesia data. This error occurs when the previous block doesn't have any votes

@AlimovSV I don't think it's a collision issue here, but it's an [existing bug](https://github.com/turinginc/credo-core-node/issues/295) that's independent of the changes in this PR. Given that finding, I'll proceed with merging here.

**Comment by macgregordennis** [comment]
@AlimovSV Great work on this, by the way.

**Pull request merged**
