### PR TITLE
Added pending nonces tracking to prevent pending tx overwriting

### PR DESCRIPTION
**Pull request by i1t**
Fixes a bug:

Previous logic allowed only 1 transaction per account until new confirmed block is written (if more than 1 transaction was submitted, all transactions were assigned with the same nonce, basing on last locally confirmed block's state). That happened silently and (very likely) unintentionally — the system successfully accepted transactions from users (not complaining on automatically assigned nonce value, which user can't even alter currently) but dropped all but one (until new validated block received / mined — that allowed one more transaction to actually go through).

### CODE REVIEW

**Comment by malroc** [comment]
Generally I'm against counting pending nonces as it is exactly what creates a nonce gap.

I'm also against timestamp approach as we can't verify that the timestamp is actually correct (we can submit a transaction with the current timestamp, and then another one with a timestamp in the past). In my opinion, having timestamp nonce is no different from having no nonce at all.

My preferred approach to this is to put a new transaction in the queue by default on the wallet app side until the previous transaction is mined. (I don't want to implement this on CCN side as we still need an option to overwrite a previously sent transaction with the same nonce in case of emergency.)

@i1t @macgregordennis @AlimovSV any thoughts/objections?

**Comment by i1t** [comment]
I don't really like the idea with queueing the transactions. Seems an unnecessary complication not present in any existing blockchain, AFAIK.

Speaking of transaction nonces, incremental nonce is a quick and easy way to determine whether a nonce is occupied or not (e.g. in Ethereum, if there are 20 transactions, any nonce greater or equal to 20 would do for pending transactions — if it's greater than 20 then tx would be waiting to be mined, no artificial queueing needed).

Alternatively, we can get all outgoing transactions for an account from the state and check whether nonce is not mined. That eliminates the need for sequntial nonces.

Timestamp-based nonces are essentially just integers. I think it's totally valid to mine a tx with timestamp 1000 and then mine one with timestamp 900. We can still call the field `nonce` if `timestamp` carries too much obligations. :-) Until a tx with timestamp 900 is not mined, it should be totally doable to override it with submitting a higher-fee one with the same timestamp (nonce). State will allow to check whether timestamp (nonce) of N was ever used by an account, and if it was used then no replay is possible.

So, I propose to abstract from timestamp-based nature of timestamp-based nonces and interpret them as integers (which they are). I propose to use integers and allow creating and filling gaps in sequence at any time. That won't allow any queueing (e.g. if current nonce is 20, users won't be able to queue transactions using nonces 21, 22, 23 etc. and then filing tx with nonce 20 to release the queue, but in practice such "queues" are rarely-if-ever intentional and result in "nonce gaps" which require expertice to eliminate and cause major confusion to regular users; in proposed scenario txs with nonces 21, 22, 23 etc. will be included in pending block without waiting for tx with nonce 20, the only condition is that nonce is previously unmined).

**Comment by i1t** [comment]
Re: https://kb.myetherwallet.com/en/transactions/what-is-nonce/ claiming that sequential nonces protect against double-spending:

As concluded in discussion on Slack, even sequential nonces allow pending transactions to be overwritten by submitting a higher-fee pending transaction with the same nonce (so receiver of the funds is anyways at risk if treating a pending transaction as confirmed, with or without sequential nonce). And if we are talking about confirmed transactions, their balance deductions are reflected in state, and double spending doesn't seem possible.

**Comment by malroc** [comment]
As discussed with @i1t in slack, Ethereum's prohibition for skipping nonce values doesn't seem to prevent any real attack scenarios but creates a serious issue (nonce gap).
So we decided to resume using sequential nonce values, but also allow skipping (i.e. a transaction with nonce 10 can follow the transaction with nonce 8) which solves nonce gap issue and doesn't seem to introduce any new ones.

**Comment by malroc** [comment]
@i1t pls resolve merging conflicts

**Comment by macgregordennis** [comment]
@i1t @malroc The code LGTM. Nice work with this improvement, Ivan.

Regarding the other comments:

First, I completely **disagree with introducing the ability to skip nonces**. Although this wouldn't introduce a vulnerability, it would eliminate an important benefit: improved control over transaction ordering. If we allow nonces to be skipped, then users and systems can only order transactions from an account by broadcasting them in a sequential order, and slowly since you'd need to check what transactions are included in a previous block (which might not be the final block for a period too). Practically, I've found transaction ordering to be useful and worth preserving. For instance, during an airdrop, I signed and broadcast more transactions from an account then the current balance could cover with with the goal of having early transactions be mined immediately and other transactions be mined when I top up the wallet.

Secondly, I **view the nonce gap issue as a solvable problem**. We've solved it in CredoEx with high reliability and it appears a good number of other wallets and services have too.

I'm also **against the timestamp proposal**. Another drawback is that it wouldn't work as well for parallel transaction production from an account, which can be nonce with sequential nonces (e.g. once thread on even nonces and another thread of odd nonces).

Given 1) requiring no nonce gaps with sequential order preserves a useful benefit of improved control of transaction order, 2) the nonce gap problem is quite solvable/manageable, and 3) the timestamp proposal is flawed, let's move forward with this PR but keep the sequential ordering requirement with integer nonces.

**Comment by i1t** [comment]
@macgregordennis, adding means to detect and handle nonce gaps and staying with sequential nonces sounds fine to me.

**Pull request merged**
