### PR TITLE
Connection reliability

### PR DESCRIPTION
**Pull request by malroc**
Marking as WIP as the code still needs more testing (and probably further improvements).

### CODE REVIEW

**Comment by malroc** [comment]
@macgregordennis should be ready now.
I expect this PR to fix most (or all) connection layer issues we currently observe.
I'll need to test these changes again once they are adopted by the whole network though.

**Comment by macgregordennis** [comment]
> I'll need to test these changes again once they are adopted by the whole network though.

@malroc I've deployed this branch to seed nodes. I'm still seeing data propagation issues. It'd be great if you could proceed with further testing of this since I think it needs more work before merging.

**Comment by malroc** [comment]
@macgregordennis sure, will do

**Comment by malroc** [comment]
@macgregordennis I have added a couple improvements, not sure that they fix the remaining bugs but I still consider that the PR is worth merging as it fixes some major connection layer issues I found

**Pull request merged**
