### PR TITLE
Channel session filters

### PR DESCRIPTION
**Pull request by malroc**

### CODE REVIEW

**Comment by malroc** [comment]
> Not functionally working yet

@macgregordennis do you see any of the appropriate records in the logs? Particularly: `Intercepting event #{evt} and sending only to session #{remote_session_id}`/`Intercepting event #{evt} without remote_session_id param (this shouldn't happen)` on the node that sends the event and/or `Received block body request: #{hash}`/`Received message on unmatched topic: #{topic}` on the node that receives it?

**Comment by macgregordennis** [comment]
> do you see any of the appropriate records in the logs?

@malroc I don't. I only see events when sent from the outgoing end of outgoing connections. Nothing shows up in the logs when I manually call/trigger events on the sending side of incoming connections. I've flipped the incoming/outgoing status between my local node and a seed node and neither works. Is it working for you locally and/or with a seed node?

**Comment by malroc** [comment]
@macgregordennis I think it should work now

**Comment by macgregordennis** [comment]
@malroc Great, I'll test it out again shortly.

**Pull request merged**
